<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;

class CreateEntreprisesTable extends Migration {

	public function up()
	{
		Schema::create('Entreprises', function(Blueprint $table) {
			$table->increments('id');
			$table->timestamps();
			$table->string('raisonSociale');
			$table->string('Sigle');
			$table->string('numContribuable');
			$table->string('numCNPS');
			$table->string('numRegistreCommerce');
			$table->integer('numStructure');
			$table->integer('numGps');
			$table->float('altitude');
			$table->float('lattitude');
			$table->float('logitude');
			$table->string('ville');
			$table->string('boitePostale');
			$table->string('villebp');
			$table->string('tel1');
			$table->string('tel2');
			$table->string('numWha');
			$table->string('fax');
			$table->string('siteweb');
			$table->string('email');
			$table->date('dateCreation');
			$table->date('datedemarrage');
			$table->boolean('avoirfilialeetranger');
			$table->boolean('partcapitaltierce');
			$table->boolean('parttierceCapital');
			$table->boolean('etrefilialtierce');
			$table->integer('capitalSocial');
			$table->integer('partprivenational');
			$table->integer('partpriveetranger');
			$table->integer('partpubliquenationale');
			$table->integer('partpubliqueetranger');
			$table->boolean('tenuecomptaecrte');
			$table->boolean('affcabcompta');
			$table->boolean('tenuecomptaformelle');
			$table->boolean('remplissagedsf');
			$table->integer('chiffaff');
			$table->integer('chiffaffexp');
			$table->integer('valajoute');
			$table->boolean('conape');
			$table->boolean('avislibreechange');
			$table->boolean('conpolitiquepub');
			$table->string('avisenvironaff');
			$table->boolean('avisrelationpubpriv');
			$table->boolean('utilordinateur');
			$table->integer('nbreordi');
			$table->integer('nbreinfo');
			$table->boolean('intranet');
			$table->boolean('internet');
			$table->boolean('ecomm');
			$table->boolean('mobilmoney');
			$table->boolean('protectenv');
			$table->boolean('dispositihhse');
			$table->boolean('lieuaisanceperso');
			$table->boolean('lieuaisanceusager');
			$table->boolean('dipositifrecyclage');
			$table->integer('montantsoutraitanceout');
			$table->integer('montantsoutraitancein');
			$table->boolean('satisfactionpartenariat');
			$table->integer('quantitedechet');
			$table->string('etapetraitement');
			$table->date('dateenreg');
			$table->string('codeINS');
			$table->integer('statut_id')->unsigned();
			$table->integer('sourceMJ_id')->unsigned();
			$table->integer('entreprise_id')->unsigned();
			$table->integer('minCom')->unsigned();
			$table->integer('Mairie')->unsigned();
			$table->integer('DGI');
			$table->integer('TribunauxAdmin');
			$table->integer('Douane');
			$table->integer('CAPEF_CCIMA');
			$table->integer('AutresFichierAdmin');
			$table->string('LibelleAutresFichier');
			$table->boolean('statutEtablissement');
			$table->string('quartier_Village');
			$table->string('pageFacebook');
			$table->string('autreMotifArretActivite');
			$table->integer('zoneIndustrielle');
			$table->integer('recensement2009');
			$table->integer('recensement2016');
			$table->integer('montantLoyer');
			$table->integer('codeEtablissementRecense');
			$table->integer('inscriptionCGA')->unsigned();
			$table->integer('connaitreAPPME')->unsigned();
			$table->string('codeFormeJuridique');
			$table->string('libelleFormeJuridique');
			$table->string('quartier');
			$table->string('repere');
			$table->string('villeLocalite');
			$table->integer('id_region')->unsigned();
			$table->string('raisonSocialeSiege');
			$table->integer('id_departement')->unsigned();
			$table->string('sigleSiege');
			$table->integer('id_arrondissement')->unsigned();
			$table->integer('numContribuableSiege');
			$table->integer('numRegistreCommerceSiege');
			$table->string('quartierSiege');
			$table->string('repereSiege');
			$table->string('villeSiege');
			$table->integer('tel1Siege');
			$table->integer('tel2Siege');
			$table->string('faxSiege');
			$table->string('emailSiege');
			$table->string('siteWebSiege');
			$table->integer('zoneFranche');
		});
	}

	public function down()
	{
		Schema::drop('Entreprises');
	}
}